### ISSUE TITLE
KeyError : u'wa

### ISSUE THREAD

**Issue by naveenkumarjk16** [SaujanyaReddy/Aspect-Based-Sentiment-Analysis-IRE-Major-Project#6]
$ python aspect_term_extractor.py
217
{u'and': {'pos_tag': u'CC'}, u'all': {'pos_tag': u'DT', u'rcmod': u'say'}, u'is': {'pos_tag': u'VBZ', u'nsubj': u'all', u'ccomp': u'magnificent'}, u'magnificent': {'pos_tag': u'JJ', u'cop': u'was', u'mark': u'that', u'nsubj': u'it'}, u'it': {'pos_tag': u'PRP'}, u'say': {'pos_tag': u'VB', u'aux': u'can', u'nsubj': u'I'}, u'there': {'pos_tag': u'RB'}, u'.': {'pos_tag': u'.'}, u'to': {'pos_tag': u'TO'}, u'other': {'pos_tag': u'JJ'}, u'was': {'pos_tag': u'VBD'}, u'that': {'pos_tag': u'IN'}, u'I': {'pos_tag': u'PRP'}, u'birthday': {'pos_tag': u'NN', u'poss': u'my'}, u'My': {'pos_tag': u'PRP$'}, u'went': {'pos_tag': u'VBD', u'xcomp': u'celebrate', u'nsubj': u'boyfriend', u'advmod': u'there', u'conj_and': u'is', u'tmod': u'night'}, u'celebrate': {'pos_tag': u'VB', u'aux': u'to', u'dobj': u'birthday'}, u'boyfriend': {'pos_tag': u'NN', u'conj_and': u'I', u'poss': u'My'}, u'can': {'pos_tag': u'MD'}, u'night': {'pos_tag': u'NN', u'det': u'the', u'amod': u'other'}, u'the': {'pos_tag': u'DT'}, u'my': {'pos_tag': u'PRP$'}}
Traceback (most recent call last):
  File "aspect_term_extractor.py", line 331, in <module>
    aspects=extractor(sentence[sid], sid)
  File "aspect_term_extractor.py", line 35, in extractor
    if(words[lem.lemmatize(word)].has_key("nsubj")):
KeyError: u'wa'

**Comment by gustavodifrafre** [comment]
I'm having the same problem!
